# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163bcd63b3c5fc2cc4b4738eae6adb94265604f92885210d2e8334f5653f96dc6853298cf7bf7b25b48468e53b9d24e8fbb4c1a4fbacacb353a22cadc95af251

test:
  secret_key_base: 283118f234488a258e0e7b6b5da317260243b8e58eb1ce33db3dc42f1112d6ab920c243617c99097c0dad25ca70381e7854d971d8ee3e131c39c3b4d3b5a21a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
